language: go
go:
- 1.13

jobs:
  include:
    - stage: style
      script:
        - ./goconst.sh
        - ./govet.sh
        - ./golint.sh
        - ./gocyclo.sh
    - stage: unit tests
      before_script: go build
      script:
        - go test -coverprofile coverage.out $(go list ./... | grep -v tests)
        - go tool cover -func=coverage.out
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: functional tests
      before_script:
        - ./run_on_ci.sh
        - go build
      script:
        - go test ./tests -v

stages:
  - style
  - unit tests
  - functional tests
