language: go
go:
- 1.13

jobs:
  include:
    - stage: style
      script:
        - ./.travis.gofmt.sh
        - ./.travis.govet.sh
        - ./.travis.golint.sh
        - ./.travis.gocyclo.sh
    - stage: unit tests
      before_script: go build
      script:
        - go test $(go list ./... | grep -v tests)
    - stage: functional tests
      before_script:
        - sh ./.travis.insightscontroller.sh
        - go build
      script:
        - go test ./tests -v

stages:
  - style
  - unit tests
  - functional tests
